Repository qgis/QGIS-Enhancement-Proposals, pull requests merged in 2025-03, with the labels that each got.

#318 QEP: Overview of widget types while configuring forms
  qep-401-overview-widget-types.md
Labels: Accepted, Project

#330 QEP 314: Relax prohibition against "auto" - exception for use of auto for variables initialized using casts
  qep-314-coding-style.md
Labels: Voting, Policy

#334 Require minimum 24 hour window for PR reviews
  qep-323-code-submission-policy.md
Labels: Accepted, Policy
